import json, hashlib

COMMON = [
  {"title": "What is dengue fever?", "text": "Dengue is a viral infection spread by Aedes mosquitoes. Symptoms include sudden high fever, severe headache, pain behind the eyes, muscle and joint pain, nausea, vomiting, and rash. Most cases recover in 1-2 weeks. Severe dengue can cause bleeding and organ failure and is a medical emergency.", "category": "Infectious Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue"},
  {"title": "What are symptoms of dengue?", "text": "Dengue symptoms appear 4-10 days after a mosquito bite and include: sudden high fever (40°C/104°F), severe headache, pain behind the eyes, muscle and joint pains, nausea, vomiting, swollen glands, and rash. Warning signs of severe dengue include severe abdominal pain, persistent vomiting, rapid breathing, and bleeding gums.", "category": "Infectious Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue"},
  {"title": "How to prevent dengue?", "text": "Prevent dengue by: using mosquito repellent, wearing long-sleeved clothing, using bed nets, eliminating standing water around your home (buckets, flower pots, tires), and keeping water containers covered. There is a dengue vaccine available in some countries for people who have had dengue before.", "category": "Prevention", "url": ""},
  {"title": "What is malaria?", "text": "Malaria is a life-threatening disease caused by Plasmodium parasites transmitted through the bites of infected female Anopheles mosquitoes. It is preventable and curable. Malaria is common in tropical and subtropical regions including Africa, South Asia, and Latin America.", "category": "Infectious Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/malaria"},
  {"title": "What are symptoms of malaria?", "text": "Malaria symptoms appear 10-15 days after infection and include: fever, chills, and sweating (often in cycles), headache, nausea and vomiting, muscle pain and fatigue, and in severe cases, jaundice, seizures, and coma. Symptoms can be mild and difficult to recognize as malaria.", "category": "Infectious Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/malaria"},
  {"title": "How is malaria treated?", "text": "Malaria is treated with antimalarial medicines. The type depends on the parasite species and severity. Common treatments include artemisinin-based combination therapies (ACTs). Early diagnosis and treatment is critical. Never self-medicate — always consult a doctor for proper diagnosis and treatment.", "category": "Treatment", "url": ""},
  {"title": "What is typhoid?", "text": "Typhoid fever is a bacterial infection caused by Salmonella typhi, spread through contaminated food and water. It is common in areas with poor sanitation. Without treatment it can be life-threatening. Typhoid is preventable through vaccination and safe food and water practices.", "category": "Infectious Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/typhoid"},
  {"title": "What are symptoms of typhoid?", "text": "Typhoid symptoms develop 1-3 weeks after exposure and include: sustained high fever (39-40°C), weakness and fatigue, stomach pain, headache, loss of appetite, and sometimes a rash of flat rose-colored spots. Without treatment, symptoms can worsen and lead to serious complications.", "category": "Infectious Disease", "url": ""},
  {"title": "What is asthma?", "text": "Asthma is a chronic lung disease that inflames and narrows the airways, causing recurring episodes of wheezing, breathlessness, chest tightness, and coughing. Triggers include allergens, air pollution, exercise, and respiratory infections. Asthma cannot be cured but can be managed with proper treatment.", "category": "Non-communicable Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/asthma"},
  {"title": "What are symptoms of asthma?", "text": "Asthma symptoms include: wheezing (a whistling sound when breathing), shortness of breath, chest tightness or pain, and coughing especially at night or early morning. Symptoms vary in frequency and severity. Severe asthma attacks can be life-threatening and require emergency treatment.", "category": "Non-communicable Disease", "url": ""},
  {"title": "What is tuberculosis TB?", "text": "Tuberculosis (TB) is a bacterial infection caused by Mycobacterium tuberculosis, mainly affecting the lungs. It spreads through the air when infected people cough or sneeze. TB is one of the top infectious disease killers worldwide but is preventable and curable with proper treatment.", "category": "Infectious Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/tuberculosis"},
  {"title": "What are symptoms of tuberculosis?", "text": "TB symptoms include: persistent cough lasting more than 2 weeks (sometimes with blood), chest pain, weakness and fatigue, weight loss, fever, and night sweats. TB can also affect other organs. Anyone with these symptoms should get tested immediately.", "category": "Infectious Disease", "url": ""},
  {"title": "What is pneumonia?", "text": "Pneumonia is an infection that inflames the air sacs in one or both lungs. It can be caused by bacteria, viruses, or fungi. Symptoms include cough with phlegm, fever, chills, and difficulty breathing. It can be life-threatening especially for elderly people, infants, and those with weak immune systems.", "category": "Infectious Disease", "url": ""},
  {"title": "What are symptoms of pneumonia?", "text": "Pneumonia symptoms include: cough (with mucus or pus), fever and chills, shortness of breath, chest pain when breathing or coughing, fatigue, nausea and vomiting, and confusion (especially in older adults). Symptoms can range from mild to severe.", "category": "Infectious Disease", "url": ""},
  {"title": "What is cholera?", "text": "Cholera is an acute diarrheal disease caused by the bacterium Vibrio cholerae, spread through contaminated water and food. It can cause severe dehydration and death within hours if untreated. Cholera is preventable through safe water, sanitation, and hygiene.", "category": "Infectious Disease", "url": ""},
  {"title": "What are symptoms of cholera?", "text": "Cholera symptoms include: sudden onset of watery diarrhea (rice-water stools), nausea and vomiting, and rapid dehydration causing muscle cramps, sunken eyes, and dry mouth. Severe cases can lead to death within hours. Oral rehydration therapy is the first line of treatment.", "category": "Infectious Disease", "url": ""},
  {"title": "What is COVID-19?", "text": "COVID-19 is a respiratory illness caused by the SARS-CoV-2 virus. Common symptoms include fever, dry cough, tiredness, and loss of taste or smell. Most people have mild illness and recover without hospital care. Seek urgent help if you have difficulty breathing or persistent chest pain.", "category": "Infectious Disease", "url": "https://www.who.int/health-topics/coronavirus"},
  {"title": "What are symptoms of COVID-19?", "text": "COVID-19 symptoms include: fever or chills, cough, shortness of breath, fatigue, muscle or body aches, headache, loss of taste or smell, sore throat, congestion, nausea or vomiting, and diarrhea. Symptoms appear 2-14 days after exposure. Emergency signs include trouble breathing and persistent chest pain.", "category": "Infectious Disease", "url": ""},
  {"title": "What is influenza flu?", "text": "Influenza (flu) is a contagious respiratory illness caused by influenza viruses. It spreads through droplets when infected people cough, sneeze, or talk. Annual vaccination is the best prevention. Most people recover in a week but it can be serious for elderly, young children, and those with chronic conditions.", "category": "Infectious Disease", "url": ""},
  {"title": "What are symptoms of flu influenza?", "text": "Flu symptoms come on suddenly and include: fever or chills, cough, sore throat, runny or stuffy nose, muscle or body aches, headaches, fatigue, and sometimes vomiting and diarrhea. Flu differs from a cold by the sudden onset and more severe symptoms.", "category": "Infectious Disease", "url": ""},
  {"title": "What is diabetes?", "text": "Diabetes is a chronic disease where the body cannot properly regulate blood sugar (glucose). Type 1 diabetes is an autoimmune condition. Type 2 is the most common and is linked to lifestyle factors. Uncontrolled diabetes can damage the heart, kidneys, eyes, and nerves.", "category": "Non-communicable Disease", "url": "https://www.who.int/news-room/fact-sheets/detail/diabetes"},
  {"title": "What are symptoms of diabetes?", "text": "Diabetes symptoms include: increased thirst and frequent urination, extreme hunger, unexplained weight loss, blurred vision, slow-healing sores, frequent infections, fatigue, and tingling or numbness in hands or feet. Type 2 diabetes may have no symptoms for years.", "category": "Non-communicable Disease", "url": ""},
  {"title": "What is hypertension high blood pressure?", "text": "Hypertension (high blood pressure) is when blood pressure is consistently too high (above 140/90 mmHg). It is called the silent killer because it often has no symptoms but can lead to heart attack, stroke, kidney disease, and vision loss. It affects 1 in 3 adults worldwide.", "category": "Non-communicable Disease", "url": ""},
  {"title": "What are symptoms of hypertension?", "text": "Hypertension usually has no symptoms, which is why it is called the silent killer. In severe cases it may cause headaches, shortness of breath, nosebleeds, flushing, dizziness, and chest pain. The only way to know is to measure blood pressure regularly.", "category": "Non-communicable Disease", "url": ""},
  {"title": "What is chickenpox?", "text": "Chickenpox is a highly contagious viral infection caused by the varicella-zoster virus. It causes an itchy blister-like rash, fever, and tiredness. It mainly affects children but can be serious in adults, pregnant women, and people with weak immune systems. A vaccine is available.", "category": "Infectious Disease", "url": ""},
  {"title": "What are symptoms of chickenpox?", "text": "Chickenpox symptoms include: itchy red spots that turn into fluid-filled blisters and then scabs, fever, tiredness, loss of appetite, and headache. The rash usually starts on the chest, back, and face then spreads. The illness lasts about 5-10 days.", "category": "Infectious Disease", "url": ""},
  {"title": "What is jaundice?", "text": "Jaundice is a yellowing of the skin and eyes caused by high levels of bilirubin in the blood. It is a symptom of underlying conditions like liver disease, hepatitis, bile duct obstruction, or blood disorders. It requires medical evaluation to find and treat the cause.", "category": "Infectious Disease", "url": ""},
  {"title": "What are symptoms of jaundice?", "text": "Jaundice symptoms include: yellow skin and whites of eyes, dark urine (tea-colored), pale or clay-colored stools, itching, fatigue, abdominal pain, weight loss, vomiting, and fever. Always consult a doctor as jaundice indicates an underlying condition that needs treatment.", "category": "Infectious Disease", "url": ""},
]

with open("data/health_knowledge.json", "r", encoding="utf-8") as f:
    existing = json.load(f)

# Prepend common diseases so they are in the first 1500 items loaded
combined = COMMON + existing
combined = combined[:14345]  # keep total reasonable

with open("data/health_knowledge.json", "w", encoding="utf-8") as f:
    json.dump(combined, f, indent=2, ensure_ascii=False)

# Update ledger
content = json.dumps(combined, indent=2, ensure_ascii=False).encode("utf-8")
new_hash = hashlib.sha256(content).hexdigest()
with open("data/health_knowledge.ledger", "w", encoding="utf-8") as f:
    f.write(new_hash)

print(f"Done. Total: {len(combined)} items. Hash: {new_hash}")
